### PR TITLE
Add

### PR DESCRIPTION
**Pull request by fullstackdev610**
## Proposed changes

Added a tag feature for the shipyard_cli.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x ] feat: non-breaking change which adds new functionality
- [ ] fix: non-breaking change which fixes a bug or an issue
- [ ] chore(deps): changes to dependencies
- [ ] test: adds or modifies a test
- [ ] docs: creates or updates documentation
- [ ] style: changes that do not affect the meaning or function of code (e.g. formatting, whitespace, missing semi-colons etc.)
- [ ] perf: code change that improves performance
- [ ] revert: reverts a commit
- [ ] refactor: code change that neither fix a bug nor add a new feature
- [ ] ci: changes to continuous integration or continuous delivery scripts or configuration files
- [ ] chore: general tasks or anything that doesn't fit the other commit types

Please indicate if your PR introduces a breaking change
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ x] I have read the [Contributing](https://github.com/linkorb/.github/blob/master/CONTRIBUTING.md) doc
- [ x] I have read the [Creating and reviewing pull requests at LinkORB guide](https://engineering.linkorb.com/topics/git/articles/reviewing-pr/) doc
- [ x] Lint and unit tests pass locally with my changes
- [ x] I have added/updated necessary documentation in the README.md or doc/ directories (if appropriate)

### CODE REVIEW

**Comment by CesarScur** [comment]
Hi Kostiantyn,

I don't think there is any problem with your change, it looks fine for me but I would like to seize the opportunity to improve. I did a video so we can pair program this review. I find that showing and working side-by-side is much more valuable than just trying to explain. Take a look:
[review](https://www.youtube.com/watch?v=wlEO91U5_ZA)



You can check my proposal here:
https://github.com/fullstackdev610/shipyard-cli/pull/1

Let me know your thoughts.

**Comment by fullstackdev610** [comment]
Hi Cesar,
Thanks for your improvements. I think your improvement is well structured and organized .
Regards,
Kostiantyn

**Comment by CesarScur** [comment]
Excellent! 

I noticed afterwards that:
* We can move the `$chartsPath` and  `$stackPath` defaults to the model property declaration. This way we can cut the checking if it is defined on the `Shipyard::__construct`;
* Some methods from `LinkORB\Shipyard\Stacks` would be better understood in the model;
* The `Config` class should be renamed to`Shipyard`;

When you come across a new feature and if these things are in the way give some thought if it is worth fixing them. Sometimes changes might be intimidating but they make the feature implementation easier in the end. And if you are uncertain, you can count on me to pair with you.

BR.

**Comment by CesarScur** [comment]
By the way,

Don't forget to merge [this PR](https://github.com/fullstackdev610/shipyard-cli/pull/1) into your change and test it before this PR merged. I was not able to test all the scenarios.

Perhaps that is another thing we need to focus in another opportunity: adding test coverage.


BR.

**Comment by fullstackdev610** [comment]
Hi Cesar,
I merged your update and just refactored following the https://github.com/linkorb/shipyard-cli/pull/2#issuecomment-1817501029
Thanks

**Comment by CesarScur** [comment]
Thanks for the update.
All good for me.
✅

**Pull request merged**
